/**
 * MicroCoin
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package Model;

import Model.Signature;
import Model.SimpleKey;
import java.math.BigDecimal;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Purchase account request
 **/
@ApiModel(description = "Purchase account request")
public class PurchaseAccountRequest {
  
  @SerializedName("accountNumber")
  private String accountNumber = null;
  @SerializedName("founderAccount")
  private String founderAccount = null;
  @SerializedName("newKey")
  private SimpleKey newKey = null;
  @SerializedName("signature")
  private Signature signature = null;
  @SerializedName("hash")
  private String hash = null;
  @SerializedName("fee")
  private BigDecimal fee = null;

  /**
   * Account to purchase
   **/
  @ApiModelProperty(required = true, value = "Account to purchase")
  public String getAccountNumber() {
    return accountNumber;
  }
  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  /**
   * Founder account, who will pay the price
   **/
  @ApiModelProperty(required = true, value = "Founder account, who will pay the price")
  public String getFounderAccount() {
    return founderAccount;
  }
  public void setFounderAccount(String founderAccount) {
    this.founderAccount = founderAccount;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public SimpleKey getNewKey() {
    return newKey;
  }
  public void setNewKey(SimpleKey newKey) {
    this.newKey = newKey;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Signature getSignature() {
    return signature;
  }
  public void setSignature(Signature signature) {
    this.signature = signature;
  }

  /**
   * Transaction hash to sign the transaction
   **/
  @ApiModelProperty(value = "Transaction hash to sign the transaction")
  public String getHash() {
    return hash;
  }
  public void setHash(String hash) {
    this.hash = hash;
  }

  /**
   * Transaction fee, if any, otherwise zero
   **/
  @ApiModelProperty(required = true, value = "Transaction fee, if any, otherwise zero")
  public BigDecimal getFee() {
    return fee;
  }
  public void setFee(BigDecimal fee) {
    this.fee = fee;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchaseAccountRequest purchaseAccountRequest = (PurchaseAccountRequest) o;
    return (this.accountNumber == null ? purchaseAccountRequest.accountNumber == null : this.accountNumber.equals(purchaseAccountRequest.accountNumber)) &&
        (this.founderAccount == null ? purchaseAccountRequest.founderAccount == null : this.founderAccount.equals(purchaseAccountRequest.founderAccount)) &&
        (this.newKey == null ? purchaseAccountRequest.newKey == null : this.newKey.equals(purchaseAccountRequest.newKey)) &&
        (this.signature == null ? purchaseAccountRequest.signature == null : this.signature.equals(purchaseAccountRequest.signature)) &&
        (this.hash == null ? purchaseAccountRequest.hash == null : this.hash.equals(purchaseAccountRequest.hash)) &&
        (this.fee == null ? purchaseAccountRequest.fee == null : this.fee.equals(purchaseAccountRequest.fee));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.accountNumber == null ? 0: this.accountNumber.hashCode());
    result = 31 * result + (this.founderAccount == null ? 0: this.founderAccount.hashCode());
    result = 31 * result + (this.newKey == null ? 0: this.newKey.hashCode());
    result = 31 * result + (this.signature == null ? 0: this.signature.hashCode());
    result = 31 * result + (this.hash == null ? 0: this.hash.hashCode());
    result = 31 * result + (this.fee == null ? 0: this.fee.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchaseAccountRequest {\n");
    
    sb.append("  accountNumber: ").append(accountNumber).append("\n");
    sb.append("  founderAccount: ").append(founderAccount).append("\n");
    sb.append("  newKey: ").append(newKey).append("\n");
    sb.append("  signature: ").append(signature).append("\n");
    sb.append("  hash: ").append(hash).append("\n");
    sb.append("  fee: ").append(fee).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
