/**
 * MicroCoin
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package Model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Signature {
  
  @SerializedName("r")
  private String r = null;
  @SerializedName("s")
  private String s = null;

  /**
   * R vector
   **/
  @ApiModelProperty(value = "R vector")
  public String getR() {
    return r;
  }
  public void setR(String r) {
    this.r = r;
  }

  /**
   * S Vector
   **/
  @ApiModelProperty(value = "S Vector")
  public String getS() {
    return s;
  }
  public void setS(String s) {
    this.s = s;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Signature signature = (Signature) o;
    return (this.r == null ? signature.r == null : this.r.equals(signature.r)) &&
        (this.s == null ? signature.s == null : this.s.equals(signature.s));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.r == null ? 0: this.r.hashCode());
    result = 31 * result + (this.s == null ? 0: this.s.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Signature {\n");
    
    sb.append("  r: ").append(r).append("\n");
    sb.append("  s: ").append(s).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
