/**
 * MicroCoin
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package hu.microcoin;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;
import com.google.gson.reflect.TypeToken;
import java.lang.reflect.Type;
import java.util.List;
import java.util.Date;
import Model.*;

public class JsonUtil {
  public static GsonBuilder gsonBuilder;

  static {
    gsonBuilder = new GsonBuilder();
    gsonBuilder.serializeNulls();
    gsonBuilder.setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");
    gsonBuilder.registerTypeAdapter(Date.class, new JsonDeserializer<Date>() {
      public Date deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        return new Date(json.getAsJsonPrimitive().getAsLong());
      }
    });
  }

  public static Gson getGson() {
    return gsonBuilder.create();
  }

  public static String serialize(Object obj){
    return getGson().toJson(obj);
  }

  public static <T> T deserializeToList(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getListTypeForDeserialization(cls));
  }

  public static <T> T deserializeToObject(String jsonString, Class cls){
    return getGson().fromJson(jsonString, getTypeForDeserialization(cls));
  }

  public static Type getListTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("Account".equalsIgnoreCase(className)) {
      return new TypeToken<List<Account>>(){}.getType();
    }
    
    if ("ChangeKeyRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<ChangeKeyRequest>>(){}.getType();
    }
    
    if ("MicroCoinError".equalsIgnoreCase(className)) {
      return new TypeToken<List<MicroCoinError>>(){}.getType();
    }
    
    if ("PurchaseAccountRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<PurchaseAccountRequest>>(){}.getType();
    }
    
    if ("Signature".equalsIgnoreCase(className)) {
      return new TypeToken<List<Signature>>(){}.getType();
    }
    
    if ("SimpleKey".equalsIgnoreCase(className)) {
      return new TypeToken<List<SimpleKey>>(){}.getType();
    }
    
    if ("TransactionRequest".equalsIgnoreCase(className)) {
      return new TypeToken<List<TransactionRequest>>(){}.getType();
    }
    
    if ("ChangeKey".equalsIgnoreCase(className)) {
      return new TypeToken<List<ChangeKey>>(){}.getType();
    }
    
    if ("PurchaseAccount".equalsIgnoreCase(className)) {
      return new TypeToken<List<PurchaseAccount>>(){}.getType();
    }
    
    if ("Transaction".equalsIgnoreCase(className)) {
      return new TypeToken<List<Transaction>>(){}.getType();
    }
    
    return new TypeToken<List<Object>>(){}.getType();
  }

  public static Type getTypeForDeserialization(Class cls) {
    String className = cls.getSimpleName();
    
    if ("Account".equalsIgnoreCase(className)) {
      return new TypeToken<Account>(){}.getType();
    }
    
    if ("ChangeKeyRequest".equalsIgnoreCase(className)) {
      return new TypeToken<ChangeKeyRequest>(){}.getType();
    }
    
    if ("MicroCoinError".equalsIgnoreCase(className)) {
      return new TypeToken<MicroCoinError>(){}.getType();
    }
    
    if ("PurchaseAccountRequest".equalsIgnoreCase(className)) {
      return new TypeToken<PurchaseAccountRequest>(){}.getType();
    }
    
    if ("Signature".equalsIgnoreCase(className)) {
      return new TypeToken<Signature>(){}.getType();
    }
    
    if ("SimpleKey".equalsIgnoreCase(className)) {
      return new TypeToken<SimpleKey>(){}.getType();
    }
    
    if ("TransactionRequest".equalsIgnoreCase(className)) {
      return new TypeToken<TransactionRequest>(){}.getType();
    }
    
    if ("ChangeKey".equalsIgnoreCase(className)) {
      return new TypeToken<ChangeKey>(){}.getType();
    }
    
    if ("PurchaseAccount".equalsIgnoreCase(className)) {
      return new TypeToken<PurchaseAccount>(){}.getType();
    }
    
    if ("Transaction".equalsIgnoreCase(className)) {
      return new TypeToken<Transaction>(){}.getType();
    }
    
    return new TypeToken<Object>(){}.getType();
  }

};
